### PR TITLE
fix: fallback empty search path to root path

### LINKED ISSUE #17: Error: Cannot find module 'package.json'
image

It runs failed on GitLab runner.

image

related https://github.com/shashkovdanil/clean-publish/issues/110

### PR DESCRIPTION
**Pull request by JounQin**
close #17

### CODE REVIEW

**Comment by antonk52** [comment]
Looks great, thank you @JounQin 

Had to lookup how cosmiconfig handles this with [`path.dirname`](https://github.com/davidtheclark/cosmiconfig/blob/18346056c9a7fdf8d7531ea5a998edfb255fc140/src/ExplorerBase.ts#L138) this looks like a great workaround.

Do you mind adding a test case for this? If not, I will merge this today/tomorrow and after adding a test case will publish a new version.

Thank you

**Comment by JounQin** [comment]
@antonk52 I'm not sure how to add a related test case. 🤣

**Comment by antonk52** [comment]
No worries, this would require adding an `it` in the [test file](https://github.com/antonk52/lilconfig/blob/master/src/spec/index.spec.ts) with the test as well as mocking `fs` module to fake `/package.json` existence in the home directory.

If you'd rather skip it this time, no pressure. I am happy to adding a test for this myself in the coming day or two 🙂

**Comment by antonk52** [comment]
Merged and released in [v2.0.3](https://github.com/antonk52/lilconfig/releases/tag/v2.0.3). Thanks a lot 🙌

**Pull request merged**
